services:
  - type: web
    name: gold-mafia-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: YOUR_BOT_TOKEN
      - key: TD_API_KEY
        value: YOUR_TWELVE_DATA_KEY
      - key: PYTHON_VERSION
        value: 3.10.12
